env:
  global:
    - CC_TEST_REPORTER_ID=2d17db8519f4e9eef0b296af57a37c2175763bf216d12018a4980595b4115f18
    - CODECOV_TOKEN=9f43f9a9-c512-428b-846d-a8fc6b800023

language: java

jdk:
  - openjdk10

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - ./gradlew build

script:
  - ./gradlew check
  - ./gradlew test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
