version: "2"

# Define several elkd nodes as a cluster configuration.
#
# Invoke the cluster with `$ docker-compose up`
services:
  elkd-1:
    build: ./
    command: ./bin/elkd-server --cluster elkd-1:9001,elkd-2:9002,elkd-3:9003,elkd-4:9004 --port 9001 --host elkd-1
    ports:
      - 9001:9001

  elkd-2:
    build: ./
    command: ./bin/elkd-server --cluster elkd-1:9001,elkd-2:9002,elkd-3:9003,elkd-4:9004 --port 9002 --host elkd-2
    ports:
      - 9002:9002

  elkd-3:
    build: ./
    command: ./bin/elkd-server --cluster elkd-1:9001,elkd-2:9002,elkd-3:9003,elkd-4:9004 --port 9003 --host elkd-3
    ports:
      - 9003:9003

  elkd-4:
    build: ./
    command: ./bin/elkd-server --cluster elkd-1:9001,elkd-2:9002,elkd-3:9003,elkd-4:9004 --port 9004 --host elkd-4
    ports:
      - 9004:9004
