version: "2"

# Define several ravine nodes as a cluster configuration.
#
# Invoke the cluster with `$ docker-compose up`
services:
  ravine-1:
    build: ./
    command: ./bin/ravine-d --cluster ravine-1:9001,ravine-2:9002,ravine-3:9003,ravine-4:9004 --port 9001 --host ravine-1
    ports:
      - 9001:9001

  ravine-2:
    build: ./
    command: ./bin/ravine-d --cluster ravine-1:9001,ravine-2:9002,ravine-3:9003,ravine-4:9004 --port 9002 --host ravine-2
    ports:
      - 9002:9002

  ravine-3:
    build: ./
    command: ./bin/ravine-d --cluster ravine-1:9001,ravine-2:9002,ravine-3:9003,ravine-4:9004 --port 9003 --host ravine-3
    ports:
      - 9003:9003

  ravine-4:
    build: ./
    command: ./bin/ravine-d --cluster ravine-1:9001,ravine-2:9002,ravine-3:9003,ravine-4:9004 --port 9004 --host ravine-4
    ports:
      - 9004:9004
