version: "2"

# Define several kerala nodes as a cluster configuration.
#
# Invoke the cluster with `$ docker-compose up`
services:
  kerala-1:
    build: ./
    command: ./bin/kerala-server --cluster kerala-1:9001,kerala-2:9002,kerala-3:9003,kerala-4:9004 --port 9001 --host kerala-1
    ports:
      - 9001:9001

  kerala-2:
    build: ./
    command: ./bin/kerala-server --cluster kerala-1:9001,kerala-2:9002,kerala-3:9003,kerala-4:9004 --port 9002 --host kerala-2
    ports:
      - 9002:9002

  kerala-3:
    build: ./
    command: ./bin/kerala-server --cluster kerala-1:9001,kerala-2:9002,kerala-3:9003,kerala-4:9004 --port 9003 --host kerala-3
    ports:
      - 9003:9003

  kerala-4:
    build: ./
    command: ./bin/kerala-server --cluster kerala-1:9001,kerala-2:9002,kerala-3:9003,kerala-4:9004 --port 9004 --host kerala-4
    ports:
      - 9004:9004
